name: 'Create Resource Group'

on:
  workflow_dispatch:
    inputs:
      env_key:
        description: 'The environment to create the reource group for'
        required: true
        type: choice
        options:
          - dev
          - test
          - prd

      project_key:
        description: 'An acronym or hyphenated project name (eg. afat / azure-function-app-template)'
        required: true
        type: string

      target_region:
        description: 'The Azure region to deploy the resource group in to'
        required: true
        type: choice
        options:
          - australiaeast

jobs:
  create_resource-group:
    name: Create Resource Group
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ format('rg-{0}-{1}', inputs.env_key, inputs.project_key) }} --location ${{  inputs.target_region  }}
            echo "Azure resource group '${{ format('rg-{0}-{1}', inputs.env_key, inputs.project_key) }}' created"
